testapp:
  build: .
  command: gunicorn -b 0.0.0.0:8000 --reload --access-logfile - "testapp.app:app"
  environment:
    PYTHONUNBUFFERED: 'true'
  volumes:
    - .:/testapp
  ports:
    - '8000:8000'
