version: "2"
services:
  postgres:
    image: tsungchh/postgres_docker:1.0.0
    volumes: 
     - /tmp/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  testapp:
    build: .
    command: gunicorn -b 0.0.0.0:8000 --reload --access-logfile - "testapp.app:app"
    
    environment:
      PYTHONUNBUFFERED: 'true'
    depends_on:
        - postgres
    links:
      - postgres
    volumes:
      - .:/testapp
    ports:
      - '8000:8000'
